#!/usr/bin/env python

import pyostat.util
import time

def main():
    """iostats main loop."""
    previous_raw_diskstats = None
    curr_uptime = 1.0
    curr_ts = 1.0
    s_hz, ncpus = pyostat.util.get_system_info()

    while True:

        raw_diskstats = pyostat.util.collect_metrics()
        prev_ts = curr_ts
        curr_ts = time.time()
        prev_uptime = curr_uptime
        curr_uptime = float(pyostat.util.read_uptime()[1])
        itv = curr_ts - prev_ts
        print itv

        if previous_raw_diskstats:
            stats = pyostat.util.generate_stats(previous_raw_diskstats,
                                                raw_diskstats, itv)
            pprint.pprint(stats['sda'])
            pprint.pprint(stats['sdb'])

        previous_raw_diskstats = raw_diskstats
        time.sleep(pyostat.util.COLLECTION_INTERVAL)

if __name__ == "__main__":
    main()
